apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deploymentnew
spec:
  selector:
    matchLabels:
      app: nginxnew
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginxnew
    spec:
      containers:
      - name: nginxnew
        image: nginx:1.14.2
        ports:
        - containerPort: 80
volumeMounts:
      - name: config-volume
          mountPath: /home/shakeer/pics
      - name: cert-volume
          mountPath: /usr/share/nginx/html

volumes:
        - name: config-volume
          configMap:
            name: csapi
        - name: cert-volume
          hostPath:
            path: /usr/share/nginx/html


