apiVersion: v1
kind: Pod
metadata:
  name: mc1
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: container1
    image: nginx:1.14.2
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  - name: container2
    image: nginx:1.14.2
    volumeMounts:
    - name: html
      mountPath: /html
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          date >> /html/index.html;
          sleep 1;
        done
