apiVersion: v1
kind: Pod
metadata:
  name: regmongo
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: container1
    image: localhost:5000/mongo
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  - name: container2
    image: localhost:5000/mongo
    volumeMounts:
    - name: html
      mountPath: /html
