apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod-1
spec:
  containers:
  - name: cm-container-1
    image: nginx
    imagePullPolicy: IfNotPresent
    env:
    - name: ENV_CITY
      valueFrom:
        configMapKeyRef:
          name: configmap-sar
          key: city

