apiVersion: v1
kind: Service
metadata:
  name: kubiaconfigmap-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31313
  selector:
    app: fortune-configmap-volume
