---
  - name: Check the remote host uptime
    hosts: localhost
    tasks:
      - include_vars: servers.yml
      - name: Execute the Uptime command over Command module
        register: uptimeoutput
        command: '{{ var1 }}'
      - name: Execute disk usage
        register: diskout
        command: '{{ var2 }}'
      

      - debug:
          var: uptimeoutput.stdout_lines
          
      - debug:
          var: diskout.stdout_lines
